version: '3.1'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: anuaimi
      POSTGRES_DB: travel
    ports:
      - "5432:5432"
